module.exports = {
  format: require('./helpers/formatHelper.js'),
  phone: require('./helpers/phoneHelper.js'),
  section: require('./helpers/addSectionHelper.js'),
  calculator: require('./helpers/calculatorHelpers.js'),
  calculatorValidation: require('./helpers/calculatorValidationHelper.js'),
  capitalraiseData: require('./helpers/capitalraiseCalculatorData.js'),
  date: require('./helpers/dateHelper.js'),
  disableEnter: require('./helpers/disableEnterHelper.js'),
  errorPage: require('./helpers/errorPageHelper.js'),
  fileList: require('./helpers/fileList.js'),
  flyPrice: require('./helpers/flyPriceFormatter.js'),
  location: require('./helpers/getCityStateByZipCode.js'),
  icons: require('./helpers/iconsHelper.js'),
  confirmOnLeave: require('./helpers/leavingConfirmationHelper.js'),
  menu: require('./helpers/menuHelper.js'),
  role: require('./helpers/roleHelper.js'),
  text: require('./helpers/textHelper.js'),
  userDocuments: require('./helpers/userDocuments.js'),
  yesNo: require('./helpers/yesNoHelper.js'),
  usaStates: require('./helpers/usaStates.js'),
  social: require('./helpers/socialLinks.js'),
  scripts: require('./helpers/scriptLoader.js'),
  video: require('./helpers/playVideo.js'),
};
