module.exports = {
  format: require('./helpers/formatHelper.js'),
  section: require('./helpers/addSectionHelper.js'),
  calculator: require('./helpers/calculatorHelpers.js'),
  calculatorValidation: require('./helpers/calculatorValidationHelper.js'),
  capitalraiseData: require('./helpers/capitalraiseCalculatorData.js'),
  crop: require('./helpers/cropHelper.js'),
  date: require('./helpers/dateHelper.js'),
  disableEnter: require('./helpers/disableEnterHelper.js'),
  dropzone: require('./helpers/dropzoneHelpers.js'),
  errorPage: require('./helpers/errorPageHelper.js'),
  fileList: require('./helpers/fileList.js'),
  flyPrice: require('./helpers/flyPriceFormatter.js'),
  location: require('./helpers/getCityStateByZipCode.js'),
  icon: require('./helpers/iconsHelper.js'),
  confirmOnLeave: require('./helpers/leavingConfirmationHelper.js'),
  menu: require('./helpers/menuHelper.js'),
  phone: require('./helpers/phoneHelper.js'),
  riskFactors: require('./helpers/riskFactorsHelper.js'),
  role: require('./helpers/roleHelper.js'),
  text: require('./helpers/textHelper.js'),
  documents: require('./helpers/userDocuments.js'),
  yesNo: require('./helpers/yesNoHelper.js'),
  usaStates: require('./helpers/usaStates.js'),
};
