var config = require('./config.js');

var titles = {
  '/': 'GrowthFountain – Equity Crowdfunding Platform', //+ config.siteTitle,
  '/companies': 'Explore Investment Opportunities' + config.siteTitle,
  '/raise-capital': 'How To Raise Capital With Equity Crowdfunding | GrowthFountain', //+ config.siteTitle,
  '/pg/overview': 'About GrowthFountain' + config.siteTitle,
  '/pg/team': 'Team ' + config.siteTitle,
  '/pg/partners': 'Partners ' + config.siteTitle,
  '/pg/contact': 'Contact Us' + config.siteTitle,
  '/pg/careers': 'Careers' + config.siteTitle,
  '/pg/news': 'Press and News ' + config.siteTitle,
  '/pg/faq': 'Frequently Asked Questions' + config.siteTitle,
  '/pg/investor-tutorial': 'Crowdfunding Investment ' + config.siteTitle,
  '/pg/education': 'The Investment Risks of Equity Crowdfunding' + config.siteTitle,
  '/pg/investorquestions': 'Equity Crowdfunding for Investors' + config.siteTitle,
  '/pg/business-tutorial': 'Crowdfunding For Entrepreneurs & Business Owners ' + config.siteTitle,
  '/pg/success-guide': 'Conducting a Successful Raise' + config.siteTitle,
  '/pg/advertising': 'How to promote your campaign' + config.siteTitle,
  '/pg/heartland-tour': 'The Heartland Tour 2017' + config.siteTitle,
  '/calculator/paybackshare/step-1': 'Revenue Share Calculator ' + config.siteTitle,
  '/calculator/whatmybusinessworth/intro': 'What’s My Business Worth?' + config.siteTitle,
  '/calculator/whatmybusinessworth/step-1':   'What’s My Business Worth?' + config.siteTitle,
  '/calculator/BusinessValuation':   'Business Valuation Calculator ' + config.siteTitle,
  '/calculator/selectCalculator2':   'Business Calculators' + config.siteTitle,
  '/calculator/establishedBusiness/intro': 'What’s My Business Worth?' + config.siteTitle,
  '/calculator/establishedBusiness/step-1': 'What’s My Business Worth?' + config.siteTitle,
  '/pg/entrepreneurquestions': 'Equity Crowdfunding for Entrepreneurs' + config.siteTitle,
  '/account/signup': 'Sign Up' + config.siteTitle,
  '/account/login': 'Log In' + config.siteTitle,
  '/account/reset': 'Reset your credentials' + config.siteTitle,
  '/pg/terms-of-use': 'Terms' + config.siteTitle,
  '/pg/privacy-policy': 'Privacy Policy' + config.siteTitle,
  '/pg/annual-privacy': 'Annual Privacy Policy' + config.siteTitle,
  '/pg/electronic-signature':  'ESIGN Disclosure' + config.siteTitle,
};

var metas = {
  '/': 'Invest in local small businesses and startups for as little as $100 with equity crowdfunding with GrowthFountain.',
  '/companies': 'Explore the companies currently raising financing on GrowthFountain. Start investing today with as little as $100. ',
  '/raise-capital': 'GrowthFountain provides resources and tutorials to teach business owners and entrepreneurs how to raise capital via local equity crowdfunding. ',
  '/pg/overview': 'Local investing equity crowdfunding GrowthFountain is changing equity crowdfunding for small businesses.',
  '/pg/team': 'At GrowthFountain, we are dedicated to helping entrepreneurs as passionate about their business as we are.',
  '/pg/partners': 'GrowthFountain is proud to partner with companies that share our passion for supporting businesses.',
  '/pg/contact': 'ADDRESS 79 Madison Ave, 5th Floor, New York, NY 10016 E-MAIL info@growthfountain.com',
  '/pg/careers': 'Openings at GrowthFountain',
  '/pg/news': 'GrowthFountain has been covered in press by established publications like TechCrunch, Cheddar TV, MasSolutions, Money Inc, Fortune, and Yahoo Finance.',
  '/pg/faq': 'What is GrowthFountain? How do I get started? What is the JOBS act? What is crowdfunding? What are the different types of crowdfunding? ',
  '/pg/investor-tutorial': 'Crowdfunding investments allow Americans to invest in local small businesses they love for as little as $100.',
  '/pg/education': 'The materials below will help you get acquainted with the GrowthFountain website and educate yourself to the offering process at GrowthFountain.',
  '/pg/investorquestions': 'How do I become an investor? How can I see the available investment opportunities? How much am I allowed to invest? What will I actually own?',
  '/pg/business-tutorial': 'Equity crowdfunding is an opportunity for American entrepreneurs and business owners to receive monetary and social capital from their biggest fans – their customer base.',
  '/pg/success-guide': 'Welcome, and thank you for your interest in raising capital on GrowthFountain.com.We intend to make the process as seamless and easy for you as possible. At the appropriate point in the process, we will make a variety of proprietary tools available to you, including links to our valuation calculators.',
  '/pg/advertising': 'Best Practices for Advertising and Communications ',
  '/pg/heartland-tour': 'We’re traveling across country on a quest for exciting companies that need to raise money to grow; from tech startups to the restaurants, bars and bricks & mortar locations across America',
  '/calculator/paybackshare/step-1': 'Use GrowthFountain\'s free Revenue Share Calculator to evaluate your future business\'s profitability if utilizing revenue share with equity crowdfunding.  ',
  '/calculator/whatmybusinessworth/intro': 'Use our free calculators to evaluate your future business, find out how much to raise, and estimate rates of return. ',
  '/calculator/whatmybusinessworth/step-1':   'Use our free calculators to evaluate your future business, find out how much to raise, and estimate rates of return.',
  '/calculator/BusinessValuation':   'Use GrowthFountain\'s free Business Evaluation Calculator to  evaluate your business and find out how much to raise in equity crowdfunding.',
  '/calculator/selectCalculator2':   'Use our free calculators to evaluate your future business, find out how much to raise, and estimate rates of return.',
  '/calculator/establishedBusiness/intro': 'Use our free calculators to evaluate your future business, find out how much to raise, and estimate rates of return',
  '/calculator/establishedBusiness/step-1': 'Use our free calculators to evaluate your future business, find out how much to raise, and estimate rates of return.',
  '/pg/entrepreneurquestions': 'Why choose GrowthFountain? How does GrowthFountain make raising capital easy? What are the advantages of equity crowdfunding?',
  '/account/signup': 'Create acccount at GrowthFountain',
  '/account/login': 'Access your GrowthFountain Account',
  '/account/reset': 'Access your GrowthFountain Account',
  '/pg/terms-of-use': 'Welcome to GrowthFountain! GrowthFountain LLC is a Delaware limited liability company that owns and operates www.GrowthFountain.com. We are headquartered in New York City at 79 Madison Avenue, 5th Floor, New York, NY 10007. ',
  '/pg/privacy-policy': 'At GrowthFountain, our most important asset is our relationship with you. This new financial movement is predicated on the idea that as a community we can do more than we do alone.',
  '/pg/annual-privacy': 'Find out what GrowthFountain does with your personal information',
  '/pg/electronic-signature':  'This E-Sign Policy and Disclosure (the “Disclosure”) from GrowthFountain Capital LLC (“GFC”, “we” or “us,” ) applies to all communications between you and GFC.'
};

module.exports = {
  title: titles,
  meta: metas
};
